export const API_ROOT = '/api/v1'

//Flash
export const RESET_MESSAGE = 'RESET_MESSAGE'
export const SET_MESSAGE = 'SET_MESSAGE'

//User
export const PROFILE_DELETE_REQUEST = 'PROFILE_DELETE_REQUEST'
export const PROFILE_DELETE_SUCCESS = 'PROFILE_DELETE_SUCCESS'
export const PROFILE_DELETE_FAILURE = 'PROFILE_DELETE_FAILURE'
export const USER_REQUEST = 'USER_REQUEST'
export const USER_SUCCESS = 'USER_SUCCESS'
export const USER_FAILURE = 'USER_FAILURE'
export const USERS_REQUEST = 'USERS_REQUEST'
export const USERS_SUCCESS = 'USERS_SUCCESS'
export const USERS_FAILURE = 'USERS_FAILURE'
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE'
export const USER_ADD = 'USER_ADD'
export const USER_REMOVE = 'USER_REMOVE'

//Image
export const IMAGE_CREATE_REQUEST = 'IMAGE_CREATE_REQUEST'
export const IMAGE_CREATE_SUCCESS = 'IMAGE_CREATE_SUCCESS'
export const IMAGE_CREATE_FAILURE = 'IMAGE_CREATE_FAILURE'
export const IMAGE_DELETE_REQUEST = 'IMAGE_DELETE_REQUEST'
export const IMAGE_DELETE_SUCCESS = 'IMAGE_DELETE_SUCCESS'
export const IMAGE_DELETE_FAILURE = 'IMAGE_DELETE_FAILURE'
export const IMAGE_ADD = 'IMAGE_ADD'
export const IMAGE_REMOVE = 'IMAGE_REMOVE'
